# Artificial Neural Network

### Importing the libraries

In [34]:
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score


In [2]:
tf.__version__

'2.0.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('../data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN
ANN are sequential, one layer after the other

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer
- When we want fully connected layer we use the Dense class where it initialised the input layer and the fully connected layer
- We just need to define the activation function, in this case relu and the number of nodes in the hiddel layer


In [21]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer
- Here we need to define the activation agaon and we used sigmoid to transform the output to a probability 
- the dimensions of the output layer is one as the prediction is going to be a probability value, the treshold of which we could define as we wish. By default if probability > 0.5 then churner 

In [23]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['Precision'])

### Training the ANN on the Training set
- We are performing batch optimisation, the weights are updated after the whole batch is processed

In [27]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.6035 - Precision: 0.1868
Epoch 2/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4977 - Precision: 0.0000e+00
Epoch 3/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4639 - Precision: 0.0000e+00
Epoch 4/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4458 - Precision: 0.6667TA: 0s - loss: 0.4430 - Precision: 1.0000  
Epoch 5/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4350 - Precision: 0.6000TA: 0s - loss: 0.4540 - Precision: 0.7
Epoch 6/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4285 - Precision: 0.6699
Epoch 7/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4219 - Precision: 0.6887
Epoch 8/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.4142 - Precision: 0.7323
Epoch 9/100
8000/8000 [==========

8000/8000 [==============================] - 0s 30us/sample - loss: 0.3347 - Precision: 0.7601
Epoch 75/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3348 - Precision: 0.7519
Epoch 76/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.3349 - Precision: 0.7586
Epoch 77/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3348 - Precision: 0.7553
Epoch 78/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3347 - Precision: 0.7697
Epoch 79/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3352 - Precision: 0.7552
Epoch 80/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.3344 - Precision: 0.7562
Epoch 81/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3347 - Precision: 0.7655
Epoch 82/100
8000/8000 [==============================] - 0s 30us/sample - loss: 0.3346 - Precision: 0.7618
Epoch 83/100
8000/8000 [=================

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [28]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

### Predicting the Test set results

In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [33]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))

[[1507   88]
 [ 201  204]]
0.8555
0.6986301369863014
